[build]
command = "npx prisma generate && yarn build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production]
command = "yarn run build && echo \"NEXTAUTH_URL=$URL\" > .env.local"

[context.deploy-preview]
command = "yarn run build && echo \"NEXTAUTH_URL=$DEPLOY_PRIME_URL\" > .env.local"