import Link from 'next/link';
import Layout from '../components/Layout';
import { Checkout } from 'checkout-sdk-node';

//const cko = new Checkout('sk_sbox_4qlnxtd6xro7e4hjhpuyyq7ixa4', { pk: 'pk_sbox_5cdu3zk4ywwlclah2kcfiq7p2qt'});
const cko = new Checkout('sk_test_3e1ad21b-ac23-4eb3-ad1f-375e9fb56481');

async function requestPayment() {
    try {
        const payment = await cko.payments.request({
            source: {
                // inferred type: "token"
                token: 'tok_bzi43qc6jeee5mmnfo4gnsnera', // Generated by Checkout.Frames
                billing_address: {
                    address_line1: 'Wall Street',
                    address_line2: 'Dollar Avenue',
                    city: 'London',
                    state: 'London',
                    zip: 'W1W W1W',
                    country: 'GB',
                },
                phone: {
                    country_code: '44',
                    number: '7123456789',
                },
            },
            currency: 'USD',
            amount: 1000,
            payment_type: 'Regular',
            reference: 'ORDER 1234',
            description: 'Mint Tea',
            customer: {
                email: 'new_user@email.com',
                name: 'John Smith',
            },
            metadata: {
                value: 'My value',
            },
        });
        console.log(payment);
    } catch (err) {
        console.log(err.name);
    }
}

async function getDetails() {
    try {
        const payment = await cko.payments.get('pay_je5hbbb4u3oe7k4u3lbwlu3zkq');
        console.log(payment);
    } catch (err) {
        console.log(err.name);
    }
}

async function uploadCert() {
    try {
        const apple = await cko.applePay.upload({
            content: 'XXXXXXX', // make sure you escape the characters
        });
        console.log(apple);
    } catch (err) {
        console.log(err.name);
    }
}

const CheckoutPage = () => (
  <Layout title='Checkout.com API'>
    <h1>Checkout.com API</h1>
    <p>This is the checkout.com API testing page</p>
    <br/>
    <button onClick={requestPayment}>
        <a>Request Payment</a>
    </button>
    <br/>
    <p>
      <Link href='/'>
        <a>Go home</a>
      </Link>
    </p>
  </Layout>
);

export default CheckoutPage;
