name: build

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ vars.AWS_REGISTRY }}/jc-app:latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ECRUSER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECRUSER_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build and push docker image
        run: docker build -t $DOCKER_IMAGE --push .