name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          architecture: 'x64'

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - run: yarn
      - run: yarn run build
